# fly.toml app configuration file generated for solitary-haze-955 on 2023-05-25T11:48:59+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "solitary-haze-955"
primary_region = "lhr"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[mounts]
   source = "data"
   destination = "/data"